declare var NSThread: any;
declare var MSDocument: any;
declare var NSStackView: any;
declare var NSMakeRect: any;
declare var NSColor: any;
declare var NSUserDefaults: any;
declare var nil: any;
declare var COScript: any;
// declare var BrowserManage: any;
declare var NSNotificationCenter: any;
declare var NSWindowDidResizeNotification: any;
